export default function FunctionSheetTab({ event }) {
  if (!event) return null;

  return (
    <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 max-w-4xl mx-auto">
      <div className="border-b pb-6 mb-6 flex justify-between items-start">
        <div>
          <h2 className="text-3xl font-bold text-gray-800">Banquet Event Order (BEO)</h2>
          <p className="text-gray-500">Event ID: #{event.id} • Date: {event.date}</p>
        </div>
        <button onClick={() => window.print()} className="bg-gray-800 text-white px-4 py-2 rounded text-sm cursor-pointer print:hidden">
          🖨️ Print BEO
        </button>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <h3 className="font-bold text-gray-700 border-b pb-2 mb-3">Event Details</h3>
          <p><span className="font-medium">Name:</span> {event.name}</p>
          <p><span className="font-medium">Type:</span> {event.type}</p>
          <p><span className="font-medium">Guests:</span> {event.guestCount} Pax</p>
          <p><span className="font-medium">Venue:</span> Emerald Hall (Default)</p>
        </div>
        <div>
          <h3 className="font-bold text-gray-700 border-b pb-2 mb-3">Client Info</h3>
          <p><span className="font-medium">Client:</span> {event.client}</p>
          <p><span className="font-medium">Contact:</span> +91 98765 43210</p>
        </div>
      </div>

      <div className="mb-8">
        <h3 className="font-bold text-gray-700 border-b pb-2 mb-3">Schedule</h3>
        <div className="grid grid-cols-3 gap-4 text-sm">
          <div className="p-3 bg-gray-50 rounded">10:00 AM - Setup Start</div>
          <div className="p-3 bg-gray-50 rounded">07:00 PM - Guest Arrival</div>
          <div className="p-3 bg-gray-50 rounded">08:30 PM - Dinner Service</div>
        </div>
      </div>

      {event.details?.items && event.details.items.length > 0 && (
        <div className="mb-8">
          <h3 className="font-bold text-gray-700 border-b pb-2 mb-3">F&B Menu Selections</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            {event.details.items.map(item => (
              <div key={item.id} className="p-3 bg-gray-50 rounded">
                <p className="font-semibold">{item.name}</p>
                <p className="text-xs text-gray-500">{item.category}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="text-center text-xs text-gray-400 mt-12 pt-4 border-t">
        Generated by Asyncotel SaaS • {new Date().toLocaleString()}
      </div>
    </div>
  );
}